### ISSUE TITLE
Share results feature creates image with .null file extension

### ISSUE THREAD

**Issue by bunchofsage** [MOVACT/voteswiper-app#17]
Hi there, I'm talking about the Android app version 3.4.2 (tested on Oneplus 3T)

The share results feature does not work as expected.

Expected:
1. Share as an image to social media e.g. to WhatsApp, Signal, Instagram
2. Only results for filtered parties are getting exported/shown (because I can change that filter to all anytime)

**Comment by mxmtsk** [comment]
Thanks for the bug report. A fix will be rolled out in app update 3.4.3
