### ISSUE TITLE
database?

### ISSUE THREAD

**Issue by che25** [MOVACT/voteswiper-app#19]
Hi Max,

super app, toll dass es open access ist. Kann man auch die Fragen mit den Antworten für alle Parteien irgendwo einsehen? Ich habe sie auf Anhieb nicht finden können.

VG

**Comment by mxmtsk** [comment]
Hallo che25,

eine Seite wo das irgendwie hübsch dargestellt ist gibt es (noch) nicht, aber in unserem API Repo findest du eine kleine Dokumentation wie du Daten aus unserer API fetchen kannst:

https://github.com/MOVACT/voteswiper-api/blob/main/API.md
